/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.35
 * Generated at: 2014-06-06 09:56:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.user.util.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {



	String signoutstatus="";



	String loginstatus="",passstatus="",mergeSatus="",mergingStatus="",share1_file="",share2_file="";

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<meta charset=\"utf-8\" />\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<title>Image_VC_RSA</title>\r\n");
      out.write("<link href=\"CSS/style.css\" rel=\"stylesheet\" />\r\n");
      out.write("<link href=\"CSS/popup.css\" rel=\"stylesheet\" />\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.print(request.getContextPath() );
      out.write("/CSS/login.css\" type=\"text/css\" />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" <script type=\"text/javascript\" src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"jquery.toastmessage.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <link href=\"jquery.toastmessage.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body background=\"Images/background.jpg\">\r\n");
      out.write("\r\n");
      out.write("\r\n");

	signoutstatus=request.getParameter("signoutstatus");
System.out.println("signoutstatus "+signoutstatus);

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");

	loginstatus=request.getParameter("loginstatus");
	passstatus=(String)request.getAttribute("passstatus");
	mergeSatus=(String)request.getAttribute("mergeSatus");
	mergingStatus=(String)request.getAttribute("mergingStatus");

      out.write("\r\n");
      out.write("<IMG SRC=\"Images/J2EE_Top copy.jpg\" width=100% height=\"15%\" BORDER=\"0\" ALT=\"\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"TabMenu\" id=\"label\" style=\"position: absolute;top: 120px;left: 800px;\"><span> \r\n");
      out.write("<img src=\"");
      out.print(request.getContextPath() );
      out.write("/Images/administrator.png\" height=\"30\" width=\"30\" />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <br>\r\n");
      out.write("<a href=\"#overlay\" id=\"button1\"><font style=\"color: #FFFF99;\"><b>Admin</b></font></a> </span> <span> &nbsp;&nbsp;\r\n");
      out.write("<img src=\"");
      out.print(request.getContextPath() );
      out.write("/Images/user.png\" height=\"30\" width=\"30\" />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <br>\r\n");
      out.write("&nbsp;&nbsp; <a href=\"#overlay_signup\" id=\"button1\"><font style=\"color: #FFFF99;\"><b>User</b></font></a> </span> \r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Admin Login Pop Up -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"overlay\">\r\n");
      out.write("\r\n");
      out.write("<div id=\"popup\"> <a href=\"\">\r\n");
      out.write("<img class=\"close_button\" src=\"Images/close.png\" /></a>\r\n");
      out.write("\r\n");
      out.write("<form class=\"login\" action=\"");
      out.print(request.getContextPath());
      out.write("/Login\" method=\"post\">\r\n");
      out.write("\r\n");
      out.write("<center><label><font style=\"font-family: Monotype Corsiva;font-size: 35px;color:#DAA520 ;\">Admin Login</font></label></center>\r\n");
      out.write("<br>\r\n");
      out.write("<label><font style=\"color: #336633;\">Admin Id</font></label>&nbsp;&nbsp;\r\n");
      out.write(" <input type=\"text\" tabindex=\"1\" class=\"input\" placeholder=\"Admin Id\" name=\"name\" required ><br>\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("<label><font style=\"color: #336633;\">Password</font></label> <input\r\n");
      out.write("\ttype=\"password\" class=\"input\" tabindex=\"2\" name=\"pass\" placeholder=\"Password\" required><br>\r\n");
      out.write("<br>\r\n");
      out.write("&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type=\"image\" id=\"\" value=\"submit\" src=\"");
      out.print(request.getContextPath());
      out.write("/Images/login.png\" alt=\"submit Button\" onMouseOver=\"this.src='");
      out.print(request.getContextPath());
      out.write("/Images/login.png'\" class=\"gradientbuttons\" width=\"20%\" height=\"10%\">\r\n");
      out.write("</form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- User Login Pop Up -->\r\n");
      out.write("\r\n");
      out.write("<div id=\"overlay_signup\">\r\n");
      out.write("<div id=\"popup\" >\r\n");
      out.write("<a href=\"\"><img class=\"close_button\" src=\"Images/close.png\" /></a> \r\n");
      out.write("\r\n");
      out.write("<form class=\"login\" action=\"");
      out.print(request.getContextPath());
      out.write("/UserLogin\" method=\"post\">\r\n");
      out.write("<center><label><font style=\"font-family: Monotype Corsiva;font-size: 35px;color:#DAA520;\">User Login</font></label></center>\r\n");
      out.write("<br>\r\n");
      out.write("<label><font style=\"color: #336633;\">User Id</font></label> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("<input type=\"text\" tabindex=\"1\" class=\"input\" name=\"name\" placeholder=\"User Id\" required><br><br>\r\n");
      out.write("\r\n");
      out.write("<label><font style=\"color: #336633;\">Password</font></label> \r\n");
      out.write("<input type=\"password\" class=\"input\" tabindex=\"2\" name=\"pass\" placeholder=\"Password\" required><br><br><br>\r\n");
      out.write("\r\n");
      out.write("&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type=\"image\" id=\"\" value=\"submit\" src=\"");
      out.print(request.getContextPath());
      out.write("/Images/login.png\" alt=\"submit Button\" onMouseOver=\"this.src='");
      out.print(request.getContextPath());
      out.write("/Images/login.png'\" class=\"gradientbuttons\" width=\"20%\" height=\"10%\">&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("<a href=\"#overlay_gallary\" id=\"\" ><font style=\"font-family: Arial;font-size: 20px;color:#336633;\">New User</font></a>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</form>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- User Register Pop Up -->\r\n");
      out.write("\r\n");
      out.write("<div id=\"overlay_gallary\">\r\n");
      out.write("<div id=\"popup\" style=\"height: 450px; width: 600px; padding: 10px;\">\r\n");
      out.write("\r\n");
      out.write("<a href=\"\"><img class=\"close_button\" src=\"Images/close.png\" /></a> \r\n");
      out.write("\r\n");
      out.write("<form class=\"login1\" action=\"");
      out.print(request.getContextPath());
      out.write("/Register\" method=\"post\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div style=\"position: absolute;top: 40px;left: 50px;\">\r\n");
      out.write("<table>\r\n");
      out.write("<tr><td align=\"center\" colspan=\"5\">\r\n");
      out.write("<label><font style=\"font-family: Monotype Corsiva;font-size: 35px;color: #DAA520;\">User Registration</font></label>\r\n");
      out.write("</td></tr>\r\n");
      out.write("\r\n");
      out.write("<tr><td>&nbsp;</td></tr>\r\n");
      out.write("<tr><td>\r\n");
      out.write("\r\n");
      out.write("<label><font style=\"color: #336633;\">User Id</font></label> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("<input type=\"text\" tabindex=\"1\" name=\"userid\" class=\"input\" placeholder=\"User Id\" required>&nbsp;&nbsp;\r\n");
      out.write("\r\n");
      out.write("<label><font style=\"color: #336633;\">Password</font></label> &nbsp;&nbsp;\r\n");
      out.write("<input type=\"password\" class=\"input\" name=\"pwd\" tabindex=\"2\" placeholder=\"Password\" required><br>\r\n");
      out.write("\r\n");
      out.write("</td></tr>\r\n");
      out.write("<tr><td>&nbsp;</td></tr>\r\n");
      out.write("<tr><td>\r\n");
      out.write("\r\n");
      out.write("<label><font style=\"color: #336633;\">User Name</font></label> \r\n");
      out.write("<input type=\"text\" tabindex=\"1\" class=\"input\" name=\"uname\" placeholder=\"User Name\" required>&nbsp;&nbsp;\r\n");
      out.write("\r\n");
      out.write("<label><font style=\"color: #336633;\">Gender</font></label> &nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("&nbsp;&nbsp;&nbsp;Male<input name=\"gender\" value=\"Male\" type=\"radio\" checked=\"true\"/>\r\n");
      out.write("\t\t\t\t\t\t&nbsp;&nbsp;&nbsp;Female<input name=\"gender\" value=\"Female\" type=\"radio\"/>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t</td></tr>\r\n");
      out.write("\t\t<tr><td>&nbsp;</td></tr>\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("<tr><td>\r\n");
      out.write("\r\n");
      out.write("<label><font style=\"color: #336633;\">Address</font></label> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("<input type=\"text\" tabindex=\"1\" name=\"addr\" class=\"input\" placeholder=\"Address\" required>&nbsp;&nbsp;\r\n");
      out.write("\r\n");
      out.write("<label><font style=\"color: #336633;\">City</font></label> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("<input type=\"text\" class=\"input\" tabindex=\"2\" name=\"city\" placeholder=\"City\" required>\r\n");
      out.write("\r\n");
      out.write("</td></tr>\r\n");
      out.write("<tr><td>&nbsp;</td></tr>\r\n");
      out.write("\r\n");
      out.write("<tr><td>\r\n");
      out.write("<br>\r\n");
      out.write("<label><font style=\"color: #336633;\">Email</font></label> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("<input type=\"text\" tabindex=\"1\" class=\"input\" name=\"email\" placeholder=\"Email\" required>&nbsp;&nbsp;\r\n");
      out.write("\r\n");
      out.write("<label><font style=\"color: #336633;\">Phone</font></label> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("<input type=\"text\" class=\"input\" tabindex=\"2\" name=\"phone\" placeholder=\"Phone\" required>\r\n");
      out.write("\r\n");
      out.write("</td></tr>\r\n");
      out.write("\r\n");
      out.write("<tr><td>&nbsp;</td></tr>\r\n");
      out.write("\r\n");
      out.write("<tr><td align=\"center\">\r\n");
      out.write("&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type=\"image\" id=\"\" value=\"submit\" src=\"");
      out.print(request.getContextPath());
      out.write("/Images/signup.jpg\" alt=\"submit Button\" onMouseOver=\"this.src='");
      out.print(request.getContextPath());
      out.write("/Images/signup.jpg'\" class=\"gradientbuttons\" width=\"20%\" height=\"90%\">\r\n");
      out.write("\r\n");
      out.write("</td></tr>\r\n");
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");

			if(Utility.parse(request.getParameter("no"))==5)
			{
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div  style=\"position: absolute;top: 500px;left: 300px;color: #336633;font-size: 20px; \">\t\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t $().toastmessage('showErrorToast', \"Sorry this user id is already exists.....!\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</script></div>\t\t\r\n");
      out.write("\t\t\t");
}

		
      out.write("\r\n");
      out.write("\t\t\r\n");
	
		int no=Utility.parse(request.getParameter("no"));
		if(no==1)
		{
      out.write("\r\n");
      out.write("\t\t<div  style=\"position: absolute;top: 500px;left: 300px;color: #336633;font-size: 20px; \">\t\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t $().toastmessage('showErrorToast', \"Invalid Id and Password ...!\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</script></div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t");
}
		if(no==3)
		{
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<div  style=\"position: absolute;top: 500px;left: 300px;color: #336633;font-size: 20px; \">\t\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t $().toastmessage('showErrorToast', \"Opp's,Something went wrong ..!\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</script></div>\t\t\r\n");
      out.write("\t\t");
}
		if(no==4)
		{
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div  style=\"position: absolute;top: 500px;left: 300px;color: #336633;font-size: 20px; \">\t\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t $().toastmessage('showSuccessToast', \"You have registered successfully!\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</script></div>\t\t\r\n");
      out.write("\t\t");
}
		
		if(no==6)
		{
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<div  style=\"position: absolute;top: 500px;left: 300px;color: #336633;font-size: 20px; \">\t\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t $().toastmessage('showSuccessToast', \"You have Logged Out Successfully!\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</script></div>\t\t\t\r\n");
      out.write("\t\t");

		}
		
		
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	if(signoutstatus==null)
	{
		
	}

	else if(signoutstatus.equals("success"))
	{
		
      out.write("\r\n");
      out.write("\t\t<div style=\"top:500px;position: absolute;left: 100px;\"><font color=red>Logged out Successfully!!!</font></div>\r\n");
      out.write("\t\r\n");
	
	session.removeAttribute("signoutstatus");
	}


      out.write('\r');
      out.write('\n');

	if(loginstatus==null)
	{
		
	}

	else if(loginstatus.equals("failed"))
	{
		
      out.write("\r\n");
      out.write("\t<br><br><br>\t\r\n");
      out.write("\t<center><h4><font color=red>Login Failed, Invalid User!!!</font></h4></center>\r\n");

	}


      out.write(" \t \r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
